- name: Mongo query operation for "{{db_name}}" - "{{col_name}}" filter="{{ filter}}"
  ansible.builtin.include_role:
     name: mongodb_query
  vars:
          mongo_db_name: "{{db_name}}"
          mongo_col_name: "{{col_name}}"
          mongo_filter:  "{{ filter}}"

- name: Mongo db query filter = "{{ filter}}"  count should be "{{expected_count}}"
  ansible.builtin.assert: { that: "{{ query_result_list|length }} == {{expected_count}}" }

