- name: Find files with "*.{{file_extension}}" in "{{item.path}}"
  find:
   paths: "{{each_file.path}}"
   patterns: "*.log"
  register: search_files

- name: Set variable for found files
  set_fact:
   found_files: "{{ search_files.files }}"

- name: Fetch log files
  ansible.builtin.include_role:
    name: fetch_files
  vars:
    source: "{{item.path }}"
    destination: "{{log_files_path | default(default_test_log_path)}}"
    with_zip: true
  with_items: "{{ found_files }}"
