- name: NSSF confns templating
  template: src=nssf_confns_mongo_json.j2 dest="{{item.confns_name}}.json"
  diff: yes
  delegate_to: mongo

- name: copy templating file to container
  ansible.builtin.shell: docker cp  "{{item.confns_name}}.json" "{{mongo_container_name}}":/
  delegate_to: mongo

- name: Mongo import operation
  ansible.builtin.shell: docker exec -it "{{mongo_container_name}}" mongoimport --mode upsert --db "{{db_name}}" --collection "{{nssf_confns_profile_col_name}}" --file "{{item.confns_name}}.json"
  delegate_to: mongo
